services:
  postgres:
    image: postgres    # Your DB of choice, replace as needed
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bos$40160
      POSTGRES_DB: appointmentServiceDB
    networks:
      - appointment-network
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - appointment-network

networks:
  appointment-network:
    driver: bridge